# sandbox environment for testing that diesel inside the built image works
# e.g. running `diesel migration run` then `diesel print-schema` should work
version: '3.1'
services:
  db:
    image: postgres:15.2-alpine3.17
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    expose:
      - 5432
  diesel:
    build: .
    restart: always
    command: tail -f /dev/null
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb